defaults:
  - task/sentiment
  - model/roberta
  - method/sgmcmc_ll
  - hyperparams/sghmc_ll

dataset:
  base_data_path: ~
  train_relative_path: ""
  test_relative_path: ""
  validation_relative_path: ""


model:
  hparams:
    tokenizer_max_length: 512
    max_grad_norm: 1
    adam_eps: 0.00000001
    adam_b2: 0.999
    gradient_checkpointing: "true"
    save_every_n_steps: 20000
    keep_top_n_checkpoints: 1
    seed: 42
    disable_jit: False
    devices: -1

sagemaker:
  account_id: ~
  iam_role: ~
  entrypoint: "benchmarks/transformers/prob_model_text_classification.py"
  instance_type: "ml.g5.2xlarge"
  profile: "default"
  region: "us-east-1"
  job_name_suffix: ~
  metrics:
    - {Name: "train_loss_step", Regex: 'loss: ([-+]?(\d+(\.\d*)?|\.\d+))'}
    - {Name: "train_accuracy_step", Regex: 'accuracy: ([-+]?(\d+(\.\d*)?|\.\d+))'}
    - {Name: "val_loss", Regex: 'val_loss: ([-+]?(\d+(\.\d*)?|\.\d+))'}
    - {Name: "val_accuracy", Regex: 'val_accuracy: ([-+]?(\d+(\.\d*)?|\.\d+))'}
    - {Name: "ind_accuracy", Regex: 'IND Test accuracy: ([-+]?(\d+(\.\d*)?|\.\d+))'}
    - {Name: "ind_ece", Regex: 'IND ECE: ([-+]?(\d+(\.\d*)?|\.\d+))'}
    - {Name: "ood_accuracy", Regex: 'OOD Test accuracy: ([-+]?(\d+(\.\d*)?|\.\d+))'}
    - {Name: "ood_ece", Regex: 'OOD ECE: ([-+]?(\d+(\.\d*)?|\.\d+))'}

output_data_path: ~
